/**
 * Database migration and seeding utilities
 *
 * Provides functions to run migrations and seed the database
 * with Phase 1 initial data.
 */

import { migrate } from "drizzle-orm/expo-sqlite/migrator";
import type { ExpoSQLiteDatabase } from "drizzle-orm/expo-sqlite";
import * as schema from "./schema";
import { allSeeds } from "./seed";
// @ts-expect-error - migrations.js is generated by drizzle-kit
import migrations from "./migrations/migrations";

/**
 * Run database migrations
 * @param db - Drizzle database instance
 */
export async function runMigrations(db: ExpoSQLiteDatabase<typeof schema>) {
  await migrate(db, migrations);
}

/**
 * Seed the database with Phase 1 initial data
 * @param db - Drizzle database instance
 */
export async function seedDatabase(db: ExpoSQLiteDatabase<typeof schema>) {
  // Insert in order to respect foreign key constraints

  // 1. Divisions
  await db.insert(schema.divisions).values(allSeeds.divisions);

  // 2. Leagues
  await db.insert(schema.leagues).values(allSeeds.leagues);

  // 3. Seasons
  await db.insert(schema.seasons).values(allSeeds.seasons);

  // 4. Positions
  await db.insert(schema.positions).values(allSeeds.positions);

  // 5. Formations
  await db.insert(schema.formations).values(allSeeds.formations);

  // 6. Formation Positions
  await db.insert(schema.formationPositions).values(allSeeds.formationPositions);

  // 7. Teams
  await db.insert(schema.teams).values(allSeeds.teams);

  // 8. Players
  await db.insert(schema.players).values(allSeeds.players);

  // 9. Team Players
  await db.insert(schema.teamPlayers).values(allSeeds.teamPlayers);

  // 10. Games
  await db.insert(schema.games).values(allSeeds.games);

  // 11. Game Periods
  await db.insert(schema.gamePeriods).values(allSeeds.gamePeriods);

  // 12. Game Player Assignments (empty assignments)
  await db.insert(schema.gamePlayerAssignments).values(allSeeds.gamePlayerAssignments);
}

/**
 * Initialize database with migrations and seed data
 * @param db - Drizzle database instance
 */
export async function initializeDatabase(db: ExpoSQLiteDatabase<typeof schema>) {
  await runMigrations(db);
  await seedDatabase(db);
}
